-- ============================================
-- Project : Personal Expense Tracker
-- File    : 01_create_tables.sql
-- ============================================

-- ============================================
-- 1. CATEGORIES TABLE
-- ============================================

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(100) NOT NULL,
    category_description VARCHAR2(255),
    is_active CHAR(1) DEFAULT 'Y'
        CHECK (is_active IN ('Y','N')),
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE
);

-- ============================================
-- 2. PAYMENT METHODS TABLE
-- ============================================

CREATE TABLE payment_methods (
    payment_method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_method_name VARCHAR2(50) NOT NULL,
    is_active CHAR(1) DEFAULT 'Y'
        CHECK (is_active IN ('Y','N'))
);

-- ============================================
-- 3. EXPENSES TABLE
-- ============================================

CREATE TABLE expenses (
    expense_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_id NUMBER NOT NULL,

    payment_method_id NUMBER NOT NULL,

    expense_date DATE DEFAULT SYSDATE,

    amount NUMBER(10,2) NOT NULL
        CHECK (amount > 0),

    description VARCHAR2(255),

    created_at DATE DEFAULT SYSDATE,

    updated_at DATE,

    CONSTRAINT fk_expense_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id),

    CONSTRAINT fk_expense_payment
        FOREIGN KEY (payment_method_id)
        REFERENCES payment_methods(payment_method_id)
);